(defpackage :dc-eclectic
  (:use :cl :cl-ppcre :trivial-utf-8 :sb-thread :sb-ext)
  (:import-from :ironclad
   :ascii-string-to-byte-array
                :byte-array-to-hex-string
   :digest-sequence
                :sha512)
  (:export
   all-permutations
   all-permutations-of-string
   comparable-hash-dump
   existing-permutations-of-string
   distinct-elements
   distinct-values
   ds
   ds-clone
   ds-from-json
   ds-get
   ds-paths
   ds-list
   ds-merge
   ds-set
   ds-to-json
   ds-type
   filename-only
   flatten
   get-unix-time
   hash-hmac-256
   hash-keys
   hash-string
   hash-values
   hashify-list
   join-paths
   log-entry
   log-entries
   path-only
   range
   run-tests
   shuffle
   strings-from-chars
   words-from-chars
   timestamp-string
   to-ascii
   universal-time-to-unix-time
   unix-time-to-universal-time
   write-log-entry
   ))
