(defpackage :dc-eclectic
  (:use :cl :cl-ppcre :trivial-utf-8 :sb-thread :sb-ext :dc-ds)
  (:import-from :ironclad
                :ascii-string-to-byte-array
                :byte-array-to-hex-string
                :digest-sequence
                :sha512)
  (:export
   all-permutations
   all-permutations-of-string
   choose-one
   comparable-hash-dump
   existing-permutations-of-string
   directory-exists-p
   distinct-elements
   distinct-values
   existing-n-gram-strings
   file-exists-p
   file-extension
   filename-only
   flatten
   get-unix-time
   hash-hmac-256
   hash-keys
   hash-string
   hash-values
   hashify-list
   index-of-max
   join-paths
   log-entry
   log-entries
   n-grams
   n-gram-strings
   path-type
   path-only
   plistp
   range
   replace-extension
   run-tests
   shuffle
   split-n-trim
   strings-from-chars
   trim
   trim-whitespace
   words-from-chars
   timestamp-string
   to-ascii
   universal-time-to-unix-time
   unix-time-to-universal-time
   verify-string
   write-log-entry
   ))
