;; docs.lisp

(in-package :dc-eclectic)

(defmacro defsection-wrapper (name (&rest options) doc-string &body body)
  `(defsection ,name ,options ,(eval doc-string) ,@body))

(defsection-wrapper @manual
  (:title "DC-ECLECTIC Reference")
  (slurp (join-paths
             (asdf:system-relative-pathname :dc-eclectic #P"")
             "intro-src.md"))
  (@overview section)
  (@installation section)
  (@functions section)
  (@variables section))

(defsection-wrapper @overview
  (:title "Overview")
  (slurp (join-paths
           (asdf:system-relative-pathname :dc-eclectic #P"")
           "overview-src.md")))

(defsection-wrapper @installation
  (:title "Installation")
  (slurp (join-paths
             (asdf:system-relative-pathname :dc-eclectic #P"")
             "installation-src.md")))

(defsection @functions
  (:title "Functions and Macros")
  "Alphabetical list of functions and macros that DC-UTILITIES defines."
  (all-permutations function)
  (all-permutations-base function)
  (all-permutations-of-string function)
  (ascii-alpha function)
  (ascii-alpha-lower function)
  (ascii-alpha-num function)
  (ascii-alpha-num-lower function)
  (ascii-alpha-num-upper function)
  (ascii-alpha-upper function)
  (ascii-char-range function)
  (ascii-numeric function)
  (base64-decode function)
  (base64-encode function)
  (choose-one function)
  (choose-some function)
  (comparable-hash-dump function)
  (copy-file function)
  (deep-copy function)
  (define-base-encoder macro)
  (denormalize-list function)
  (directory-exists-p function)
  (distinct-elements function)
  (distinct-strings function)
  (distinct-values function)
  (exclude function)
  (exclude-regex function)
  (existing-n-gram-strings function)
  (existing-permutations-of-string function)
  (file-exists-p function)
  (file-extension function)
  (filename-only function)
  (flatten function)
  (freeze function)
  (getenv function)
  (has function)
  (has-some function)
  (hash-hmac-256 function)
  (hash-keys function)
  (hash-string function)
  (hash-values function)
  (hashify-list function)
  (index-of-max function)
  (join-paths function)
  (leaf-directory-only function)
  (n-gram-strings function)
  (n-grams function)
  (n-grams-of-list function)
  (normalize-list function)
  (path-only function)
  (path-type function)
  (plist-keys function)
  (plistp function)
  (rand function)
  (random-hex-number function)
  (random-number function)
  (random-string function)
  (range function)
  (replace-extension function)
  (root-path function)
  (safe-decode function)
  (safe-encode function)
  (safe-sort function)
  (setenv function)
  (shell-command-background function)
  (shell-command-running-p function)
  (shell-command-to-string function)
  (shell-command-wait function)
  (shuffle function)
  (singular function)
  (slurp function)
  (spew function)
  (split-n-trim function)
  (thaw function)
  (to-ascii function)
  (tree-get function)
  (tree-put macro)
  (trim function)
  (trim-whitespace function)
  (uuid function)
  (verify-string function))

(defsection @variables
  (:title "Special Variables")
  "Exported special variables."
  (*alphabet-alphanum* variable)
  (*alphabet-bitcoin* variable)
  (*alphabet-alphanum-upper* variable))

(defun generate-readme ()
  (let* ((file-name (join-paths
                      (asdf:system-relative-pathname :dc-eclectic #P"")
                      "README.md"))
          (raw-doc (with-output-to-string (s)
                     (document @manual :format :markdown :stream s)))
          (final-doc (re:regex-replace-all ":public: " raw-doc "")))
    (spew final-doc file-name)
    t))
